version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/app
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}

    command: uvicorn main:app --host 0.0.0.0 --port ${API_HOST} --reload

